name: 'docker'

on:
    create:
        tags:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v1

            -   name: Inject slug/short variables
                uses: rlespinasse/github-slug-action@v2.x

            -   name: Get build time
                uses: 1466587594/get-current-time@v1
                id: current-time

            -   name: docker registry login
                run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            -   name: Set up Docker Buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    version: latest

            -   name: Build docker multiarch images and push to Registry
                run: |
                    docker buildx build \
                    --platform=linux/386,linux/amd64,linux/arm/v7,linux/arm64 \
                    --build-arg BUILD_DATE=${{ steps.current-time.outputs.time }} \
                    --build-arg BUILD_VERSION=${{ env.GITHUB_REF_SLUG }} \
                    --build-arg VCS_REF=${{ env.GITHUB_SHA_SHORT }} \
                    --output "type=image,push=true" \
                    --file ./Dockerfile . \
                    -t "ghcr.io/${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}" \
                    -t "ghcr.io/${{ github.repository }}:latest"
